[build]
f  # Serve static site from public/
  publish = "public"
  command = "echo 'Static deploy from public/'"

[build.environment]
  # Ensure a modern Node for Expo
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
# (Removed Expo-specific cache header)

[[headers]]
  for = "/assets/logo/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"