[build]
  # Publish directory
  publish = "."
  
  # Build command (none needed for static site)
  command = "echo 'Static site - no build needed'"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200