[build]
  # Directory to change to before starting a build
  base = "public"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "public"
  
  # Default build command
  command = "echo 'No build step required'"

[[redirects]]
  # Handle SPA routing - redirect all routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
