[build]
  # Publish the Expo web export directory
  publish = "dist"
  
  # Build the Expo web app on Netlify
  command = "npm ci --legacy-peer-deps && npx --yes expo export --platform web && mkdir -p dist/assets && cp -R public/assets/* dist/assets/"

[build.environment]
  # Ensure a modern Node for Expo
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_expo/static/js/web/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/logo/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"